# Generated by Django 5.0.1 on 2024-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendenceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='code',
            field=models.IntegerField(max_length=100),
        ),
    ]
