# Generated by Django 5.0.1 on 2024-02-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendenceapp', '0002_alter_scanner_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='attendance_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
