# Generated by Django 5.0.1 on 2024-02-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendenceapp', '0004_alter_scanner_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='attendance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='scanner',
            table=None,
        ),
    ]
