# Generated by Django 5.0.1 on 2024-02-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendenceapp', '0006_alter_scanner_code_alter_scanner_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='attendance_count',
        ),
    ]
