# Generated by Django 5.0.1 on 2024-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendenceapp', '0007_remove_scanner_attendance_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='attendance_count',
            field=models.IntegerField(default=0),
        ),
    ]
