# Generated by Django 5.0.1 on 2024-02-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendenceapp', '0008_scanner_attendance_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='attendance_count',
        ),
    ]
